dist: trusty

git:
  depth: false

services:
  - docker

language: go

go:
- 1.14.x

addons:
  sonarcloud:
    organization: "iwarapter-github"

script:
  - go mod vendor || travis_terminate 1;
  - go mod verify || travis_terminate 1;
  - make test-and-report || travis_terminate 1;
  - sonar-scanner || travis_terminate 1;
